# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 879)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(690, 30, 171, 31))
        self.refreshButton.setObjectName("refreshButton")
        self.cityesTable = QtWidgets.QTableWidget(self.centralwidget)
        self.cityesTable.setGeometry(QtCore.QRect(160, 90, 901, 741))
        self.cityesTable.setMinimumSize(QtCore.QSize(800, 0))
        self.cityesTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cityesTable.setShowGrid(True)
        self.cityesTable.setObjectName("cityesTable")
        self.cityesTable.setColumnCount(4)
        self.cityesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(3, item)
        self.citiesComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.citiesComboBox.setGeometry(QtCore.QRect(360, 30, 201, 31))
        self.citiesComboBox.setObjectName("citiesComboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        item = self.cityesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MESTO"))
        item = self.cityesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Temperature [°C]"))
        item = self.cityesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Wind speed [km/h]"))
        item = self.cityesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pressure [HPa]"))
