# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1450, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1450, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(700, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.refreshButton.setFont(font)
        self.refreshButton.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background: #C0C0C0;\n"
"    color: #000;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background: #FFF;\n"
"    color: #000;\n"
"    border-color:  #C0C0C0;\n"
"    border-width: 1.2px;\n"
"    border-style:inset;\n"
"}")
        self.refreshButton.setObjectName("refreshButton")
        self.cityesTable = QtWidgets.QTableWidget(self.centralwidget)
        self.cityesTable.setGeometry(QtCore.QRect(150, 110, 1050, 741))
        self.cityesTable.setMinimumSize(QtCore.QSize(1050, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cityesTable.setFont(font)
        self.cityesTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cityesTable.setShowGrid(True)
        self.cityesTable.setObjectName("cityesTable")
        self.cityesTable.setColumnCount(5)
        self.cityesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cityesTable.setHorizontalHeaderItem(4, item)
        self.citiesComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.citiesComboBox.setGeometry(QtCore.QRect(310, 60, 201, 31))
        self.citiesComboBox.setStyleSheet("QComboBox {\n"
"    border-radius: 5px;\n"
"    background: #C0C0C0;\n"
"    color: #000;\n"
"}")
        self.citiesComboBox.setObjectName("citiesComboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 20, 441, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1450, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.refreshButton.setText(_translate("MainWindow", "REFRESH"))
        item = self.cityesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MESTO"))
        item = self.cityesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Temperature [°C]"))
        item = self.cityesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Wind direction"))
        item = self.cityesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Wind speed [km/h]"))
        item = self.cityesTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pressure [HPa]"))
        self.label.setText(_translate("MainWindow", "ARSO meteo: Current weather reports"))
